# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-05 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.IntegerField(default=-1)),
                ('patient', models.IntegerField(default=-1)),
                ('comment', models.CharField(default='This comment was blank', max_length=1024)),
                ('date', models.DateTimeField(auto_now=True)),
                ('private', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DietRestriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(default='No name given', max_length=50)),
                ('category', models.CharField(default='Not Categorized', max_length=40)),
                ('patient', models.IntegerField(default=-1)),
                ('doctor', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='DietSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(default='No name given', max_length=50)),
                ('category', models.CharField(default='Not Categorized', max_length=40)),
                ('servings', models.IntegerField(default=0)),
                ('patient', models.IntegerField(default=-1)),
                ('doctor', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='Dr.', max_length=10)),
                ('firstname', models.CharField(default='Doctor', max_length=25)),
                ('lastname', models.CharField(default='Nurse', max_length=25)),
                ('email', models.EmailField(default='doctor@placeholder.com', max_length=254)),
                ('phone', models.IntegerField(default='6130000000')),
                ('specialty', models.CharField(default='Proctology', max_length=50)),
                ('photo', models.ImageField(max_length=255, null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.IntegerField(default=1)),
                ('patient', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.IntegerField(default=-1)),
                ('patient', models.IntegerField(default=-1)),
                ('description', models.CharField(default='No description available', max_length=2048)),
                ('file', models.FileField(max_length=255, null=True, upload_to='media/')),
                ('date', models.DateTimeField(auto_now=True)),
                ('private', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nothing', max_length=50)),
                ('brandName', models.CharField(default='N/A', max_length=50)),
                ('servingQuantity', models.IntegerField(default=1)),
                ('servingUnit', models.CharField(default='None', max_length=50)),
                ('calories', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('totalFats', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('satFats', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('cholesterol', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('sodium', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('carbs', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('sugar', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('protein', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('thumb', models.URLField(default='None available')),
                ('highres', models.URLField(default='None available')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('patient', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.IntegerField(default=-1)),
                ('patient', models.IntegerField(default=-1)),
                ('medication', models.CharField(default='Tylenol', max_length=255)),
                ('reason', models.CharField(default='No reason available', max_length=1024)),
                ('dose', models.CharField(default='1 a day', max_length=255)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False)),
                ('firstname', models.CharField(default='Testy', max_length=25)),
                ('lastname', models.CharField(default='Tester', max_length=25)),
                ('email', models.EmailField(default='tester@placeholder.com', max_length=254)),
                ('password', models.CharField(default='fakepassword', max_length=40)),
                ('phone', models.CharField(default='5191231234', max_length=20)),
                ('age', models.IntegerField(default=-1)),
                ('weight', models.IntegerField(default=-1)),
                ('height', models.IntegerField(default=-1)),
                ('gender', models.CharField(default='Male', max_length=10)),
                ('healthcard', models.IntegerField(default=0)),
                ('status', models.CharField(default='Stable', max_length=25)),
                ('lastseen', models.IntegerField(default=-1)),
                ('reason', models.CharField(default='Knife fights. Yes, plural.', max_length=2048)),
                ('photo', models.ImageField(max_length=255, null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.IntegerField(default=-1)),
                ('date', models.DateTimeField(auto_now=True)),
                ('symptom', models.CharField(default='Sniffles', max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.IntegerField(default=-1)),
                ('patient', models.IntegerField(default=-1)),
                ('testname', models.CharField(default='Scan', max_length=130)),
                ('reason', models.CharField(default='No reason given', max_length=2048)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
